README.md, custom_components/open_epaper_link/__init__.py, custom_components/open_epaper_link/hub.py, custom_components/open_epaper_link/imagegen.py, custom_components/open_epaper_link/sensor.py, custom_components/open_epaper_link/services.yaml, docs/drawcustom/supported_types.md
**This is a breaking commit!**
- Changed usage of drawcustom to use of entitiy_id, so no need to configure width, height and mac anymore.
- Changed format of hwmap in hub.py to support width and height per hwtype. 
- Changed state update to write hwtype, width, height into entity attribute.
=> bugfix hub, changed drawcustom to entity_id 

custom_components/open_epaper_link/sensor.py
Fixes an error I was seeing in the homeassistant logs, due to my openepaper AP not reporting temperature:
```
2023-10-14 03:58:00.733 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.ap_temp fails
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 554, in async_update_ha_state
await self.async_device_update()
File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 781, in async_device_update
await hass.async_add_executor_job(self.update)
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/root/.homeassistant/custom_components/open_epaper_link/sensor.py", line 124, in update …
```
=> Fix TypeError when temperature isn't present

custom_components/open_epaper_link/__init__.py, custom_components/open_epaper_link/services.yaml
When using "drawcustom", it often requires quite a few tries and adjustment to get it "right".
Currently, all changes are pushed to the tag, but it usually is sufficent to look at the jpg created in HASS to check if the "design" look good. No need to "stress" the AP or use battery on every single test. 
With this change, it's possible to add a "dry-run: true" and it will create the jpg, but not upload it to the AP/tag.
=> Add "dry-run" to "draw custom"

README.md
FIxed example service call to use the newer target selector syntax since mac: is no longer supported
=> Fix example service call

custom_components/open_epaper_link/imagegen.py, docs/drawcustom/supported_types.md
Add anchor parameter that defaults to 'la' which is the PIL default. Keeping the default as 'la' makes this change backwards compatible with existing configurations without anchor.
Adding this feature allows icon layouts that follow similar placement as text elements.
=> Add anchor parameter to icon

docs/drawcustom/supported_types.md
- Add consistent headings and definitions.
- Use yaml syntax highlighting and remove leading indentation in code blocks.
- Fix a couple duplicates in sample configs. Fixes #65.
- Add bold to parameter names.
- Move `max_width` to `text`, since it's only supported there, not in `multiline`.
- Minor typo/spelling/grammar fixes.
=> Improve `draw_custom` documentation.

docs/drawcustom/supported_types.md
Handy to know we can set line spacing and alignment for text, as well as multiline.
=> Update to text documentation for parameter available

custom_components/open_epaper_link/imagegen.py, docs/drawcustom/supported_types.md
Optionally allow icon names to be prefixed with "mdi:". This allows you to reuse the same icon names as home assistant. Especially helpful when reusing an icon from an entity in home assistant to display on a tag.
=> Support icon names with "mdi:" prefix

custom_components/open_epaper_link/imagegen.py
Also search in the icon aliases for the supplied icon name.
I'm using the state of a weather entity to determine an icon. However, the weather entity state often doesn't 100% correlate to the icon name, but to one of its aliases. For example the state will be `partlycloudy`, while the icon's name is `(weather-)partly-cloudy`, one of the aliases is `(weather-)partlycloudy` though.
So with allowing the icon's aliases I won't have to manually convert names, but I can just use `weather-{{ states('weather.some_entity') }}` (hopefully, I haven't checked all weather states & corresponding icons).
=> allow icon aliases

custom_components/open_epaper_link/imagegen.py, docs/drawcustom/supported_types.md
Add `visible` option to all drawcustom elements. Useful to show or hide certain elements using templates.
Example:
```yaml
- type: text
value: "Feed the dog"
...
visibile: "{{ is_state('binary_sensor.dogs_need_food', 'on') }}"
```
=> Add `visible` option to all drawcustom elements

README.md, custom_components/open_epaper_link/imagegen.py, docs/drawcustom/supported_types.md
Currently the documentation warns that the rectangle may cover previous information. However, using `None` as the color allows not drawing anything. Allowing a `null` yaml value for colors solves this.
=> Enable use of `null` to not draw rectangle inside

custom_components/open_epaper_link/imagegen.py
There is a usage of `math.floor` in the `plot` draw option but the `math` module was not imported before.
=> add missing `math` import

custom_components/open_epaper_link/imagegen.py
Previously all negative values were ignored in the `plot` functionality, as `id_decimal` did not recognize them as decimal values…
=> `is_decimal` now also recognizes negative values

custom_components/open_epaper_link/imagegen.py
This update now checks for icon name, if that fails, THEN it checks through the aliases of icons. 
Looks like the icon list is checked A-Z, so some icons which have aliases higher than the actual name (e.g. water, alias = liquid-spot) gets picked before the actual name (icon liquid-spot has an alias of water) has chance to be picked.
=> Fix from recent PR 80 to allow MDI Alias icon names (after name is checked first)

custom_components/open_epaper_link/imagegen.py, docs/drawcustom/supported_types.md
Set as optional the params of `multiline` that are optional in `text`.
Also, minor markdown fixes (Autoformat).
To simplify switching between text and multiline, and make multiline easier to use.
=> Match drawcustom multiline params with text

custom_components/open_epaper_link/imagegen.py
Handy for when you are creating a tag with LOTS of icons and one or more do not exists - the error message now tells you which. Not that I misspelled one at all....!
=> Added icon name to error message if doesn't exist in MDI.

docs/drawcustom/supported_types.md
Added document note for accessing locally sored images for the dlimg function - their "url" needs to be the correct path to them from the base config folder.
=> Updated documentation for locally stored image for dlimg

custom_components/open_epaper_link/imagegen.py
Labels in plots are currently drawn with antialiasing. The reason was a missing `fontmode` specification. This should fix this.
=> Fix font antialiasing in plot labels

custom_components/open_epaper_link/camera.py, custom_components/open_epaper_link/imagegen.py, custom_components/open_epaper_link/manifest.json, custom_components/open_epaper_link/util.py
=> Remove hardcoded paths to config and use relative paths

custom_components/open_epaper_link/imagegen.py, docs/drawcustom/supported_types.md
Added support for Data URI in dlimg.
Example:
url: data:image/gif;base64,R0lGODdhAQABAPAAAP8AAAAAACwAAAAAAQABAAACAkQBADs
=> Support Data URI in dlimg

custom_components/open_epaper_link/imagegen.py
I am not sure why this was done in the first place, maybe because support for it was only added in Pillow v8? This way, multiline text can properly be drawn if for example the text is fully centered.
=> Do not remove anchor when drawing multiline text

custom_components/open_epaper_link/imagegen.py, docs/drawcustom/supported_types.md
See https://github.com/OpenEPaperLink/Home_Assistant_Integration/pull/180#issuecomment-2402261058 for why.
=> Switch default anchor for text from `lt` to `la`.

README.md, docs/drawcustom/supported_types.md
Readme and supported types doc updated
=> Improved Readme

custom_components/open_epaper_link/imagegen.py, custom_components/open_epaper_link/services.py, docs/drawcustom/supported_types.md
Half-colors (50% black, 50% accent) can rendered in a nice checkerboard style if we use `dither=2` when uploading the image to the AP.
We now use dither style 2 as default, i.e., if passing `dither=False` in the service data, that way we can use the 50% colors and it does not seem to have any significant other effect.
When showing photos, passing `dither=True` in the service data will use the dither style 1, just as before, existing setups that rely on dithering continue to work as before.
We introduce the following colors:
- `half_black`, `hb`, `gray`, `grey`, `g`
- `half_accent`, `ha`
- `half_red`, `hr`
- `half_yellow`, `hy`
=> Introducing 50% colors

custom_components/open_epaper_link/services.py, custom_components/open_epaper_link/services.yaml, custom_components/open_epaper_link/translations/de.json, docs/drawcustom/supported_types.md, tests/drawcustom/conftest.py
OpenEPaperLink allows for three dithering options:
- disabled
- floyd-steinberg
- ordered
With the dither option as bool, we were limited to two of these options, now as int, we can have all! It defaults to option 2, ordered dithering.
=> Allow all three dithering methods

custom_components/open_epaper_link/image_decompressor.py, custom_components/open_epaper_link/tag_types.py
This pull request includes changes to the `custom_components/open_epaper_link` module to standardize the naming of the `rotate_buffer` attribute across various functions and classes. The most important changes include updating the attribute name in the `TagType` class and all its references in the `image_decompressor.py` file.
Standardizing attribute naming:
* [`custom_components/open_epaper_link/image_decompressor.py`](diffhunk://#diff-1edca680162f1aed1587c8aac2352f02036e82d94c1415dc458a24b46f363b9bL21-R25): Changed all instances of `rotate_buffer` to `rotatebuffer` in the `decode_esl_raw`, `to_image`, and other related functions. [[1]](diffhunk://#diff-1edca680162f1aed1587c8aac2352f02036e82d94c1415dc458a24b46f363b9bL21-R25) [[2]](diffhunk://#diff-1edca680162f1aed1587c8aac2352f02036e82d94 …
=> fixed rotatebuffer

custom_components/open_epaper_link/sensor.py
This import seems to be mistakenly added since it's not used. For those of us that don't use switchbot on Home Assistant, this import breaks the integration.
=> Remove unused switchbot.adv_parser import

.github/workflows/tests.yml, .gitignore, pyproject.toml, requirements.txt, requirements_test.txt
- Add requirements_test.txt for test package requirements.
- Create pyproject.toml for pytest.ini instead of building in github workflow.
- Unpin homeassistant version in requirements.txt.
- Add missing websockets library to requirements.txt.
- Add rename_me saved image from tests to gitignore.
=> Restructure test setup.

custom_components/open_epaper_link/imagegen.py, docs/drawcustom/supported_types.md
'text' allows to have colours in 'value' so let allow the same for 'multiline'
=> multiline: allow to use 'parse_colors' option

custom_components/open_epaper_link/button.py, custom_components/open_epaper_link/hub.py, custom_components/open_epaper_link/manifest.json, custom_components/open_epaper_link/text.py, custom_components/open_epaper_link/translations/de.json, custom_components/open_epaper_link/translations/en.json
This pull request includes several enhancements and new features for the `custom_components/open_epaper_link` integration. The most important changes include the addition of a new button entity for deep sleep mode, updating the device name dynamically, and adding text entities for tag names/aliases.
New Features:
* [`custom_components/open_epaper_link/button.py`](diffhunk://#diff-0416c363a9b2580f00759078fe94cde50dca78087e3af56daf60352e26304530R42): Added a new `DeepSleepButton` entity to handle deep sleep commands. [[1]](diffhunk://#diff-0416c363a9b2580f00759078fe94cde50dca78087e3af56daf60352e26304530R42) [[2]](diffhunk://#diff-0416c363a9b2580f00759078fe94cde50dca78087e3af56daf60352e26304530R231-R261)
* [`custom_components/open_epaper_link/text.py`](diffhunk://#diff-25a45eb877fe009601e7781 …
=> Add deep sleep button, tag alias textbox

custom_components/open_epaper_link/switch.py, custom_components/open_epaper_link/translations/de.json, custom_components/open_epaper_link/translations/en.json, custom_components/open_epaper_link/translations/pt.json
This pull request adds a new feature to the `open_epaper_link` custom component, enabling the option to show timestamps on ESLs. The changes include updates to the switch configuration and translations for multiple languages.
Key changes:
* Added the "Show Timestamp" option to the switch configuration in `custom_components/open_epaper_link/switch.py`.
Translation updates:
* Added the "Show Timestamp" translation to the German language file `custom_components/open_epaper_link/translations/de.json`.
* Added the "Show Timestamp" translation to the English language file `custom_components/open_epaper_link/translations/en.json`.
* Added the "Show Timestamp" translation to the Portuguese language file `custom_components/open_epaper_link/translations/pt.json`.
=> feat: Add Show timestamp switch to the AP device

custom_components/open_epaper_link/services.py
Before you could only use device_ids and no Labels.
Labels work now.
Example:
```
[...]
actions:
- action: open_epaper_link.drawcustom
data:
background: white
dither: "1"
ttl: 600
dry-run: false
payload:
- type: dlimg
url: >-
https://example.com/foobar.png
x: 0
"y": 0
xsize: 296
ysize: 152
rotate: 270
rotate: 0
target:
label_id: eink_label
[...]
```
=> added support for Labels in OpenEPaperLink: Draw Custom Image

custom_components/open_epaper_link/hub.py
Previous behaviour was to break cycle upon error that lead to incomplete or empty result. In turn that lead to deletion of some tags (and re-addition later). Now in case of error code makes up to 10 retries (total, for all pages) and then re-raises an exception instead of ignoring it.
Fixes #252
=> Handle errors when fetching all tags, add retries

custom_components/open_epaper_link/imagegen.py
This pull request modifies the `custom_components/open_epaper_link/imagegen.py` file to update the method for retrieving the current time. Specifically, it replaces `dt.utcnow()` with `dt.now()` in the `_draw_plot` function for better alignment with local time handling.
* [`custom_components/open_epaper_link/imagegen.py`](diffhunk://#diff-bcf01b5b48cda13595626c76b54bc63950b51964dfff419009c25c459995b848L2091-R2091): Changed from `dt.utcnow()` to `dt.now()` in `_draw_plot` to use local time instead of UTC.
fixes #263 and #262
=> fix(plot): update time retrieval to use local time instead of UTC

custom_components/open_epaper_link/manifest.json
This fixes #279 as required for HA 2025.8 onwards because apparently that requires a different (newer) websocket lib version.
=> Change websocket requirement to >= 14.2

README.md
This pull request updates the installation instructions for the Home Assistant integration in the `README.md` file. The main change is the replacement of the step-by-step HACS installation instructions with a direct badge link for easier access.
Documentation improvements:
* Replaced the numbered list of HACS installation steps with a Home Assistant badge link to streamline the installation process for users.
=> chore(docs): Replace HACS instructions with direct badge link
