- README.md
- custom_components/open_epaper_link/hub.py
- custom_components/open_epaper_link/imagegen.py
- custom_components/open_epaper_link/services.yaml
First of all, thanks for the integration, working quite nicely :)
I've done some spelling fixes (disclaimer: I'm not a native speaker) and added the missing documentation for the third character in the formatting options.
> Spelling and documentation fixes

- custom_components/open_epaper_link/__init__.py
- custom_components/open_epaper_link/imagegen.py
- custom_components/open_epaper_link/services.yaml
- custom_components/open_epaper_link/strings.json
- custom_components/open_epaper_link/translations/de.json
- custom_components/open_epaper_link/translations/en.json
- Fixed label for ip in config_flow by adding translation for DE and EN
- added new service draw custom image
> fixed label in config_flow and new service Draw Custom Image

- README.md
- custom_components/open_epaper_link/__init__.py
- custom_components/open_epaper_link/hub.py
- custom_components/open_epaper_link/imagegen.py
- custom_components/open_epaper_link/services.yaml
- added documentation for drawcustom to readme
- added rotation functionality on draw
> documentation & rotation

- custom_components/open_epaper_link/imagegen.py
This PR fixes artifacs. This is done by using the pallete mode from PIL with a corresponding white/black/red color pallete.
> fix(drawcustom): Fixed artifacts by using palette image mode

- custom_components/open_epaper_link/__init__.py
- custom_components/open_epaper_link/imagegen.py
> Fix bug in dlimg service and preliminary support for 7.5" display

- custom_components/open_epaper_link/__init__.py
- custom_components/open_epaper_link/imagegen.py
- custom_components/open_epaper_link/services.yaml
Using display sizes provided by hass for downloadimage.
Fixed colors for palette images.
> fix: Fixed line4,5 and downloadimage

- custom_components/open_epaper_link/sensor.py
Small typo corrected (conected -> connected)
> Typo corrected

- README.md
Installation steps are easier now that this project is an accepted project in HACS
> Update README.md Instructions because project is included in HACS repositories now

- docs/drawcustom/supported_types.md
Handy to know that dry-run is a thing!
> Update drawcustom documentation to show data

- custom_components/open_epaper_link/imagegen.py
A suggestion to shorten the code by converting lots of uses of
~~~python
if "var" not in element:
var = default_value
else:
var = element["var"]
~~~
to
~~~python
var = element.get("var", default_value)
~~~
> Use dict.get() with default values to shorten code

- custom_components/open_epaper_link/imagegen.py
- custom_components/open_epaper_link/manifest.json
- docs/drawcustom/supported_types.md
An extension to the `drawcustom` functionality to plot the history of home assistant entities.
> Plot graph functionality

- custom_components/open_epaper_link/hub.py
> Fix reconnecting to the hub on disconnect.

- .devcontainer.json
- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
- requirements.txt
- scripts/develop
- scripts/lint
- scripts/setup
VSCode Devcontainers make it really easy for new developers to contribute and test their work.
Based off the work from https://github.com/ludeeus/integration_blueprint
> Setup VSCode Devcontainers

- custom_components/open_epaper_link/imagegen.py
Support yellow with new 2.60b OpenEPaperLink firmware
> Added yellow color for OpenEPaperLink Firmware 2.6

- custom_components/open_epaper_link/imagegen.py
- docs/drawcustom/supported_types.md
- Change imagegen logging level from info to debug to prevent log spam
- Add stroke support for text and multiline
- Updated documentation to reflect addition of stroke support
> Enhance logging and imagegen

- custom_components/open_epaper_link/manifest.json
Fix issue that the integration allows multipaple AP's, while it in fact does not.
> Single device only

- custom_components/open_epaper_link/imagegen.py
- docs/drawcustom/supported_types.md
Text position is off slightly if enabled
> Added progress bar element

- custom_components/open_epaper_link/imagegen.py
- docs/drawcustom/supported_types.md
Added circle, ellipse and rounded corners for rectangle
> Added more shapes

- custom_components/open_epaper_link/__init__.py
- custom_components/open_epaper_link/icons.json
- custom_components/open_epaper_link/services.yaml
- custom_components/open_epaper_link/util.py
Service calls for tag actions like clear pending, force refresh, reboot, scan channels and AP reboot added
> Added service calls for common tag actions

- custom_components/open_epaper_link/hub.py
- custom_components/open_epaper_link/hw_map.py
hwmap is now a separate file for better readability
added M2 2.9 BW to hw_map
> Refactored hwmap to be a separate file

- custom_components/open_epaper_link/hw_map.py
add support for lilygo t-panel (the rs485 version with an ESP32-S3 and ESP32-G2) https://www.lilygo.cc/products/t-panel-s3
> Update hw_map.py for lilygo t-panel

- custom_components/open_epaper_link/__init__.py
- custom_components/open_epaper_link/button.py
- custom_components/open_epaper_link/hub.py
- custom_components/open_epaper_link/select.py
- custom_components/open_epaper_link/switch.py
- custom_components/open_epaper_link/text.py
- custom_components/open_epaper_link/util.py
SubghzChannel is not working yet because i have no ap with subghz capabilities to test this
> Added AP Settings entities

- custom_components/open_epaper_link/imagegen.py
- docs/drawcustom/supported_types.md
> Dynamically change default text anchor.

- custom_components/open_epaper_link/__init__.py
- custom_components/open_epaper_link/button.py
- custom_components/open_epaper_link/camera.py
- custom_components/open_epaper_link/config_flow.py
- custom_components/open_epaper_link/hub.py
- custom_components/open_epaper_link/icons.json
- custom_components/open_epaper_link/imagegen.py
- custom_components/open_epaper_link/select.py
- custom_components/open_epaper_link/sensor.py
- custom_components/open_epaper_link/services.py
- custom_components/open_epaper_link/services.yaml
- custom_components/open_epaper_link/switch.py
- custom_components/open_epaper_link/text.py
- custom_components/open_epaper_link/translations/de.json
- custom_components/open_epaper_link/translations/en.json
- custom_components/open_epaper_link/util.py
- docs/drawcustom/supported_types.md
- It is recommended to completely remove and reinstall the integration when upgrading to this version
- Automations now use device triggers instead of entity triggers - you will need to update your existing automations
- Previous: Entity triggers using entity_id
> Rewrite of hub and integration should be mostly done

- README.md
- docs/drawcustom/supported_types.md
This pull request includes extensive updates to the `README.md` and `docs/drawcustom/supported_types.md` files to enhance documentation for the Home Assistant Integration for the OpenEPaperLink project. The changes focus on improving the structure, clarity, and comprehensiveness of the documentation, including new sections, updated examples, and migration instructions.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R14-L56): Added a new "Requirements" section detailing the necessary hardware for the integration. Updated the "Features" section to better describe device integration, configuration controls, and display controls. Introduced a "Migrating to Version 1.0" section to guide users through breaking changes and service migration. …
> Updated README.md

- custom_components/open_epaper_link/config_flow.py
- custom_components/open_epaper_link/imagegen.py
- custom_components/open_epaper_link/translations/de.json
- custom_components/open_epaper_link/translations/en.json
- custom_components/open_epaper_link/translations/pt.json
- docs/drawcustom/supported_types.md
- tests/drawcustom/conftest.py
This pull request introduces support for custom fonts in the OpenEPaperLink integration and updates the related documentation and translations. The most important changes include adding the custom font directories configuration, updating the initialization and configuration steps, and enhancing the documentation to guide users on specifying and using custom fonts.
fixes #233
fixes #243
* [`custom_components/open_epaper_link/config_flow.py`](diffhunk://#diff-d45d17955ddd218cd3189d4ba38c9e6014e389a341fc082611bafa44b13f84fcL18-R18): Added support for custom font directories in the configuration flow, including new options and default values. [[1]](diffhunk://#diff-d45d17955ddd218cd3189d4ba38c9e6014e389a341fc082611bafa44b13f84fcL18-R18) …
> General fixes

- README.md
- custom_components/open_epaper_link/__init__.py
- custom_components/open_epaper_link/hub.py
- custom_components/open_epaper_link/services.py
- custom_components/open_epaper_link/services.yaml
This pull request includes several changes to the `open_epaper_link` custom component to improve functionality, enhance performance, and fix issues. The most important changes include adding battery optimization tips in the `README.md`, updating file removal operations to be asynchronous, and various enhancements to tag handling in the `hub.py` file.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R63-R72): Added battery optimization tips to help maximize tag battery life by adjusting latency settings.
* [`custom_components/open_epaper_link/__init__.py`](diffhunk://#diff-b24960228cc6184419b055fcf0693d6b9f63c9df76d1d51ccd272a3edfa9ca88L82-R112): Updated file removal operations to be asynchronous, improving performance and avoiding blocking …
> Fix TTL time unit, clarify dither options, tags are now all discovered on startup, and removed on deletion

- custom_components/open_epaper_link/__init__.py
- custom_components/open_epaper_link/button.py
- custom_components/open_epaper_link/camera.py
- custom_components/open_epaper_link/config_flow.py
- custom_components/open_epaper_link/device_trigger.py
- custom_components/open_epaper_link/hub.py
- custom_components/open_epaper_link/image_decompressor.py
- custom_components/open_epaper_link/imagegen.py
- custom_components/open_epaper_link/select.py
- custom_components/open_epaper_link/sensor.py
- custom_components/open_epaper_link/services.py
- custom_components/open_epaper_link/switch.py
- custom_components/open_epaper_link/tag_types.py
- custom_components/open_epaper_link/text.py
- custom_components/open_epaper_link/util.py
This pull request includes extensive documentation improvements for the `custom_components/open_epaper_link` integration, adding detailed docstrings to various functions and classes to enhance code readability and maintainability. The most important changes include updates to the `__init__.py` and `button.py` files.
* `custom_components/open_epaper_link/__init__.py`:
- Added detailed docstrings to the `async_setup_entry`, `start_websocket`, `async_update_options`, `async_unload_entry`, `async_remove_entry`, and `async_remove_storage_files` functions, explaining their purpose, arguments, and return values. [[1]](diffhunk://#diff-b24960228cc6184419b055fcf0693d6b9f63c9df76d1d51ccd272a3edfa9ca88L21-R41) [[2]](diffhunk://#diff-b24960228cc6184419b055fcf0693d6b9f63c9df76d1d51ccd272a3edfa9ca88L40- …
> Add docstrings throughout the repo

- custom_components/open_epaper_link/services.py
I added retry logic for the image upload function in case of a timeout sending the data. It retries 3 times, each time doubling the backoff time (starts at 2 seconds).
> Add retry on timeout för image upload

- README.md
Add note that Configuration is only needed in AP mode.
> Update README.md: Add note that Configuration is only needed in AP mode.
